music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'
#This is the actuall app name on the left pane which is music.
#So clarifies when we call music:detail in the index it calls details of
# music app not any other app

urlpatterns = [
    # /music/
    # TUT 29 url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'), #as_view() is predefinded as we need a fun since we changes to class

    url(r'^register/$', views.USerFormView.as_view(), name='register'),

    # /music/album_id/
    # TUT 29 url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # PK above is since we need primary key as querying the DB so we replace with album_id

# After changing to class in Tut 29 we don't use fav function
# # /music/album_id/favorite/
#     url(r'^(?P<album_id>[0-9]+)/favorite$', views.favorite, name='favorite'),

    #/music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    # No primary key as we are adding new album

    #/music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    #/music/album/2/delete/
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from music import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #url(r'^$', views.index, name='site_index'),
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),

]

if settings.DEBUG: #if it is true it means we are in development mode
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_tittle = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()


    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.pk})
    #when we addd a new album it take the primary key ^ and takes us to detail view page

    def __str__(self):
        return self.album_tittle + " - " + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_tittle = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_tittle

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    #widget is to change the password to stars

    class Meta: #information about your class
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login #loging keeps the user logged in while they are browsing
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View
from .models import Album
from .forms import UserForm

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'
    # if we dont write the above list it return the variable to index.html on object_list var

    def get_queryset(self): #predefined function which queries the DB
        return Album.objects.all()

class DetailView(generic.DeleteView): #detail view of one object
    model = Album #model is predefined
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_tittle', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_tittle', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class USerFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    #display a blank form
    def get(self, request):
        form = self.form_class(None) #reference to the actual form
        return  render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)# when user clicks submit

        if form.is_valid():

            user = form.save(commit=False) # creates a user object but stores locally locally not in DB

            # cleaned and normallised data, like Date
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returns user object if credentials are correct
            user = authenticate(username=username, passowrd=password)#checks for user nad password against DB to see if it exists

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
        # This is like else part. If the user is banned or can't login, returns back to the same form(no error)
        return render(request, self.template_name, {'form': form})




    '''

In TUT 29 we change all the things to objects and list of object but changing to class

#from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
# Tut 15 from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import Http404


from .models import Album, Song

def index(request):
    all_albums = Album.objects.all()
    # Tut 15 template = loader.get_template('music/index.html') # here we load the template
    context = {
        'all_albums': all_albums,
    }




    Tut 14:
    html = ''
    for album in all_albums:
        url = '/music/' + str(album.id) + '/'
        html += '<a href="' + url + '">' + album.album_tittle + '</a><br>'


    # Tut 15 return HttpResponse(template.render(context, request)) #whenever you have view you need to return something

    return render(request,'music/index.html', context)

#def index(request):
 #   return HttpResponse("<h1>This is the music homepage</h1>")

def detail(request, album_id):
  #Tut 16 return HttpResponse("<h2>details for album Id:" + str(album_id) + "</h2>")
    #It just returns the album ID which we don't want anymore



    TUT 21
    try:
        #album = Album.objects.get(pk=album_id)
        album = Album.objects.filter(id=album_id).get()
    except Album.DoesNotExist:
        raise Http404("Album Does not exist")




    # instead of above try clause we can include get_object_or_404
    album = get_object_or_404(Album, pk=album_id)

    return render(request, 'music/detail.html', {'album': album})


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    #now check if the song exists
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])

    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album': album,
            'error_message': "you did not select a valid song!!!!",
        })
    else:
        if  selected_song.is_favorite:
            selected_song.is_favorite = False
            selected_song.save()
        else:
            selected_song.is_favorite = True
            selected_song.save()
            #comment


    return render(request, 'music/detail.html', {'album': album})
    '''

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a new Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <dive class="col-sm-12 col-md-7">

            <div class="panel panel-default">

                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <dive class="form-group" >
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </dive>
                </form>

            </div>

        </dive>

    </div>

</div>

{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    {% block tittle %}
    {% endblock %}
    </title>
{% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
    <link href='https://fonts.googlepis.com/css?family=Satisfy' rel='stylesheet' type='text/css'/>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>




</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>
        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Searh</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>

            </ul>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block tittle %}
Album Details
{% endblock %}

{% block body %}
<img src="{{album.album_logo}}">

<h1>{{ album.album_tittle}}</h1>
<h3>{{album.artist }}</h3>


    {% for song in album.song_set.all %}

            {{ song.song_tittle }}
            {% if song.is_favorite %}
                <img src="https://assets.bonanzastatic.com/images/product_review/full_star_small.png" />
            {% endif %}
        <br>
    {% endfor %}

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.error}}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag}}</label>
    <div class="col-sm-10">{{ field }} </div>
</div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
        {% if all_albums %}
            {% for album in all_albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>

            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="#">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">

        <dive class="col-sm-12 col-md-7">

            <div class="panel panel-default">
                <h3>Create a new account</h3>
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <dive class="form-group" >
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </dive>
                </form>

            </div>

        </dive>

    </div>

</div>

{% endblock %}